- hosts: "all"
  tasks:
    - name: Install packages for ceph
      yum:
        name:
          - python39
          - systemd
          - docker-ce
          - chrony
          - lvm2
        state: present