apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  namespace: default
spec:
  containers:
  - name: tomcat
    image: tomcat
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: tomcat-logs
      mountPath: /usr/local/tomcat/logs

  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c","tail -f /logs/catalina*.log"]
    volumeMounts:
    - name: tomcat-logs
      mountPath: /logs
  volumes:
  - name: tomcat-logs
    emptyDir: {}