apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo ok > /tmp/health
          sleep 10
          rm -f /tmp/health
          sleep 600
      livenessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 1
        exec:
          command:
            - cat
            - /tmp/health